# spring.application.name=LetMeCook Backend
#
# # OAuth2 Discord Registration
# spring.security.oauth2.client.registration.discord.provider=discord
# spring.security.oauth2.client.registration.discord.client-id=1430163580048904334
# spring.security.oauth2.client.registration.discord.client-secret=xI-K15HhnrqkAQgGXNLh7qRw4leAcfvn
# spring.security.oauth2.client.registration.discord.client-authentication-method=post
# spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.discord.scope[0]=identify
# spring.security.oauth2.client.registration.discord.redirect-uri=http://localhost:8080/login/oauth2/code/discord
#
# # OAuth2 Sign-In-With-Discord
# spring.security.oauth2.client.provider.discord.authorization-uri=https://discordapp.com/api/oauth2/authorize
# spring.security.oauth2.client.provider.discord.token-uri=https://discordapp.com/api/oauth2/token
# spring.security.oauth2.client.provider.discord.user-info-uri=https://discordapp.com/api/users/@me
# spring.security.oauth2.client.provider.discord.user-name-attribute=username
